Navbar section
zaman2031/htmltask2 pull request #3
Opened 2022-05-23 07:05 UTC by zaman2031

2022-05-24 09:03 UTC, omair445 requested changes

2022-05-24 09:03 UTC, omair445 commented on my-app/src/App.js
> +       {/* <Profile /> */}
Remove all the commented out code from your PR.

2022-05-24 09:03 UTC, omair445 commented on my-app/src/components/Navbar.scss
> +
Remove extra spaces.

2022-05-24 09:03 UTC, omair445 commented on my-app/src/components/Profile.jsx
> +import React from 'react';
Remove this component file from your PR as it is not related to the PR.

2022-05-24 09:03 UTC, omair445 commented on my-app/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
Are all these fonts families are using in the project?

2022-05-24 09:03 UTC, omair445 commented on my-app/src/index.js
> +reportWebVitals();
Please explain the use of the method.

2022-05-24 09:05 UTC, omair445 commented
@zaman2031 
Remove these files from your PR.
package-lock
manifest
robot.txt
app.test
setuptest

2022-05-24 09:34 UTC, zaman2031 commented on my-app/src/App.js
> +       {/* <Profile /> */}
removed

2022-05-24 09:37 UTC, zaman2031 commented on my-app/src/components/Navbar.scss
> +
removed

2022-05-24 09:41 UTC, zaman2031 commented on my-app/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
No

2022-05-24 09:43 UTC, zaman2031 commented on my-app/src/components/Profile.jsx
> +import React from 'react';
removed

2022-05-24 09:45 UTC, zaman2031 commented on my-app/src/index.js
> +reportWebVitals();
Need more Searching I know little bit about this function.

2022-05-25 09:26 UTC, nb-1231 requested changes

2022-05-25 09:26 UTC, nb-1231 commented on my-app/src/components/Navbar.jsx
> -import newLogo from '../Logos/logo.png';
use assets folder for images

2022-05-25 09:26 UTC, nb-1231 commented on my-app/src/components/Navbar.jsx
> +                    <img src={logo} alt="" />
fill out the alt property

2022-05-25 09:26 UTC, nb-1231 commented on my-app/src/components/Navbar.jsx
> +                        <li className='N-character'>N</li>
use a better name for classes

2022-05-25 09:26 UTC, nb-1231 commented on my-app/src/components/Navbar.jsx
remove extra spaces

2022-05-25 09:27 UTC, nb-1231 commented
navbar content must be aligned

2022-05-25 09:38 UTC, zaman2031 commented on my-app/src/components/Navbar.jsx
> -import newLogo from '../Logos/logo.png';
redolved

2022-05-25 09:41 UTC, zaman2031 commented on my-app/src/components/Navbar.jsx
> +                    <img src={logo} alt="" />
resolved

2022-05-25 09:46 UTC, zaman2031 commented on my-app/src/components/Navbar.jsx
> +                        <li className='N-character'>N</li>
resolved

2022-05-25 09:55 UTC, zaman2031 commented on my-app/src/components/Navbar.jsx
resolved

2022-06-02 07:46 UTC, MuneebSVS requested changes

2022-06-02 07:46 UTC, MuneebSVS commented on my-app/public/index.html
> +    -->
Commented out code still exist. I have mentioned you to specifically look into whole PR and remove it.

2022-06-02 07:46 UTC, MuneebSVS commented on my-app/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
Remove the extra fonts.

2022-06-02 07:46 UTC, MuneebSVS commented on my-app/src/index.js
> +reportWebVitals();
Have you search for this method.

2022-06-02 08:13 UTC, zaman2031 commented on my-app/public/index.html
> +    -->
This come by default with create react app . I think whole pr means that files on which i am working . Sorry for that I am removing this and push again thanks.

2022-06-02 08:41 UTC, MuneebSVS commented
Your PR now contain the changes for the profile, info section etc that shouldn't be there.

2022-06-03 06:30 UTC, MuneebSVS approved these changes

2022-06-03 06:30 UTC, MuneebSVS commented on my-app/public/index.html
> +    -->
If the file are showing in your PR its your responsibility either it is created by you or it is generate by default.
You need to take a closer look at you code while pushing it not just use "git add ." .

2022-06-03 06:45 UTC, merged

2022-06-03 06:47 UTC, zaman2031 commented
Next time i will be careful about my previous mistakes .


On Fri, Jun 3, 2022 at 11:46 AM Muhammad Zaman <
***@***.***> wrote:

> ok sir
>
> On Fri, Jun 3, 2022 at 11:30 AM MuneebSVS ***@***.***>
> wrote:
>
>> ***@***.**** approved this pull request.
>> ------------------------------
>>
>> In my-app/public/index.html
>> <https://github.com/zaman2031/htmltask2/pull/3#discussion_r887698881>:
>>
>> > +    <!--
>> +      manifest.json provides metadata used when your web app is installed on a
>> +      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
>> +    -->
>> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
>> +    <!--
>> +      Notice the use of %PUBLIC_URL% in the tags above.
>> +      It will be replaced with the URL of the `public` folder during the build.
>> +      Only files inside the `public` folder can be referenced from the HTML.
>> +
>> +      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
>> +      work correctly both with client-side routing and a non-root public URL.
>> +      Learn how to configure a non-root public URL by running `npm run build`.
>> +    -->
>> +    <title>React App</title>
>> +  </head>
>> +  <body>
>> +    <noscript>You need to enable JavaScript to run this app.</noscript>
>> +    <div id="root"></div>
>> +    <!--
>> +      This HTML file is a template.
>> +      If you open it directly in the browser, you will see an empty page.
>> +
>> +      You can add webfonts, meta tags, or analytics to this file.
>> +      The build step will place the bundled scripts into the <body> tag.
>> +
>> +      To begin the development, run `npm start` or `yarn start`.
>> +      To create a production bundle, use `npm run build` or `yarn build`.
>> +    -->
>>
>> If the file are showing in your PR its your responsibility either it is
>> created by you or it is generate by default.
>> You need to take a closer look at you code while pushing it not just use
>> "git add ." .
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/zaman2031/htmltask2/pull/3#pullrequestreview-993185105>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZCU5YUXVVETUMZFJSZ2VWLVNGRA5ANCNFSM5WUZBUVA>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-10-11 08:27 UTC, zaman2031 commented
ok sir

On Fri, Jun 3, 2022 at 11:30 AM MuneebSVS ***@***.***> wrote:

> ***@***.**** approved this pull request.
> ------------------------------
>
> In my-app/public/index.html
> <https://github.com/zaman2031/htmltask2/pull/3#discussion_r887698881>:
>
> > +    <!--
> +      manifest.json provides metadata used when your web app is installed on a
> +      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
> +    -->
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
> +    <!--
> +      Notice the use of %PUBLIC_URL% in the tags above.
> +      It will be replaced with the URL of the `public` folder during the build.
> +      Only files inside the `public` folder can be referenced from the HTML.
> +
> +      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
> +      work correctly both with client-side routing and a non-root public URL.
> +      Learn how to configure a non-root public URL by running `npm run build`.
> +    -->
> +    <title>React App</title>
> +  </head>
> +  <body>
> +    <noscript>You need to enable JavaScript to run this app.</noscript>
> +    <div id="root"></div>
> +    <!--
> +      This HTML file is a template.
> +      If you open it directly in the browser, you will see an empty page.
> +
> +      You can add webfonts, meta tags, or analytics to this file.
> +      The build step will place the bundled scripts into the <body> tag.
> +
> +      To begin the development, run `npm start` or `yarn start`.
> +      To create a production bundle, use `npm run build` or `yarn build`.
> +    -->
>
> If the file are showing in your PR its your responsibility either it is
> created by you or it is generate by default.
> You need to take a closer look at you code while pushing it not just use
> "git add ." .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zaman2031/htmltask2/pull/3#pullrequestreview-993185105>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZCU5YUXVVETUMZFJSZ2VWLVNGRA5ANCNFSM5WUZBUVA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>